name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.1', '8.2']
        dependencies: ['normal', 'authoritative']

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      if: matrix.dependencies == 'normal'
      run: composer install --prefer-dist
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Install dependencies
      if: matrix.dependencies == 'authoritative'
      run: composer install --prefer-dist --classmap-authoritative
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run Phpunit
      run: composer run phpunit

    - name: Run Infection
      run: |
        XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-xml cov --log-junit=cov/result.junit.xml
        ./vendor/bin/infection --coverage=cov

    - name: Run PhpCs
      run: ./vendor/bin/phpcs -q --report=checkstyle | ./vendor/bin/cs2pr

    - name: Check dependency usage
      run: ./vendor/bin/composer-require-checker check ./composer.json
