name: Run CI

on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --classmap-authoritative

    - name: Check code style
      run: composer run style-check -- -q --report=checkstyle | ./vendor/bin/cs2pr

    - name: Run unit tests
      run: composer run test-unit

    - name: Run mutation tests
      run: |
        composer run test-unit -- --coverage-xml cov --log-junit=cov/result.junit.xml
        composer run test-mutation -- --coverage=cov
      env:
        XDEBUG_MODE: coverage

    - name: Check dependency usage
      run: composer run composer-check
